"""QM9's official "uncharacterized" list -- the 3054 molecules whose deposited geometry
and deposited SMILES are not the same molecule.

--------------------------------------------------------------------------------------
Why this layer is needed
--------------------------------------------------------------------------------------
QM9 contains a group of molecules for which **the B3LYP/6-31G(2df,p) equilibrium
geometry deposited upstream and the SMILES deposited upstream are not the same
molecule**. The cause is that the initial geometry (generated by Corina) rearranged or
dissociated during the DFT optimisation, while the data set went on recording the
original SMILES in its index.

Ramakrishnan, Dral, Rupp & von Lilienfeld, *Sci. Data* **1**, 140022 (2014) list these
molecules in a separate file, `uncharacterized.txt`, **3054** of them (2.3% of 133885).
The criterion is the file's own, verbatim:

    "the Corina generated Cartesian coordinates and the B3LYP/6-31G(2df,p) equilibrium
     geometry lead to different SMILES and InChI strings when parsed through the
     program Openbabel"

--------------------------------------------------------------------------------------
This repository was caught by it once (defect 63)
--------------------------------------------------------------------------------------
`dsgdb9nsd_003838`, whose SMILES in the index is `N=C1N=CON=N1` (a six-membered ring).
It is on the list, and the SMILES the list gives for "parsed from the B3LYP geometry" is

    [NH][C][N]C=O.N#N          <- **that full stop is two fragments**

Measuring the same geometry ourselves: **7 bonds, 2 connected components** (`NCNCOHH`
and `NN`), that is, the N2 has already come off, exactly as the list says. MACE did not
break this and CREST did not break this -- **it arrived from QM9 already broken**.

Before this gate was added, it ran all the way through CREST (1399 seconds) only to be
caught at the graph-isomorphism step.

--------------------------------------------------------------------------------------
One conservative choice that has to be stated
--------------------------------------------------------------------------------------
The 3054 rows carry three SMILES columns: the original GDB17 one, the one parsed from
the B3LYP geometry, and the one parsed from the Corina geometry. **Measured: in 48 of
the 3054 rows (1.6%) the first two columns are identical** -- meaning the **B3LYP
geometry of those 48 molecules is in fact sound**, and they are on the list only
because OpenBabel parsed Corina's initial guess as something else. This module
**still removes all of them**:

  * the list is a published, citable, bit-for-bit reproducible object; sieving it again
    by a criterion of our own would replace a published criterion with an unpublished one;
  * the cost is 48 / 133885 = **0.036%** of the data.

This is a **stated-consequence convention that may be changed**, not a derived
criterion.
"""
from pathlib import Path

from .. import S0_ROOT

#: The list, shipped with the repository. **Never fetched from the network** -- a
#: product has to be reproducible offline.
DEFAULT_PATH = S0_ROOT / "data" / "qm9-uncharacterized" / "uncharacterized.txt"

#: Download source, written down here for provenance.
SOURCE_URL = "https://ndownloader.figshare.com/files/3195404"
SOURCE_CITATION = ("Ramakrishnan, Dral, Rupp & von Lilienfeld, "
                   "Sci. Data 1, 140022 (2014), supplementary file uncharacterized.txt")

#: How many entries the file should hold. **A criterion, not a hint** -- a wrong count
#: raises rather than continuing silently.
EXPECTED_COUNT = 3054

_CACHE = {}


def _parse(path):
    """Parse `uncharacterized.txt`.

    Layout (the file's own): the first 9 lines are explanation and a header, the last
    line is a rule; column 1 of a data row is the 1-based QM9 index, and columns 2, 3
    and 4 are the GDB17 SMILES, the SMILES parsed from the B3LYP geometry, and the
    SMILES parsed from the Corina geometry.

    Rows are **not sliced by line number** here -- one extra blank line upstream would
    shift everything silently. They are recognised by "column 1 is all digits", which
    makes the criterion explicit and immune to small changes of layout.
    """
    rows = []
    for line in Path(path).read_text(encoding="utf-8", errors="replace").splitlines():
        f = line.split()
        if len(f) >= 4 and f[0].isdigit():
            rows.append(dict(index=int(f[0]), smiles_gdb17=f[1],
                             smiles_b3lyp_xyz=f[2], smiles_corina=f[3]))
    return rows


def load(path=None):
    """Read the list and return (rows, a provenance record). Cached per path."""
    path = Path(path or DEFAULT_PATH)
    key = str(path)
    if key in _CACHE:
        return _CACHE[key]
    if not path.exists():
        raise FileNotFoundError(
            "the QM9 uncharacterized list is not at {}.\n"
            "It ships with the repository; if it really is missing, fetch it from {}"
            .format(path, SOURCE_URL))
    rows = _parse(path)
    if len(rows) != EXPECTED_COUNT:
        raise ValueError(
            "the QM9 uncharacterized list parsed to {} entries, expected {} -- either "
            "the file or the parsing is wrong, refusing to continue."
            .format(len(rows), EXPECTED_COUNT))
    n_geom_bad = sum(1 for r in rows if r["smiles_gdb17"] != r["smiles_b3lyp_xyz"])
    prov = dict(
        path=str(path),
        source_url=SOURCE_URL, citation=SOURCE_CITATION,
        n_entries=len(rows),
        n_deposited_geometry_disagrees_with_smiles=n_geom_bad,
        n_only_corina_disagrees=len(rows) - n_geom_bad,
        note="all {} entries are removed; in {} of them the B3LYP geometry does agree "
             "with the SMILES, which makes this a conservative choice with a stated "
             "consequence (0.036% of the data)".format(
                 len(rows), len(rows) - n_geom_bad))
    _CACHE[key] = (rows, prov)
    return rows, prov


def indices(path=None):
    """The set of 1-based QM9 indices."""
    rows, _ = load(path)
    return {r["index"] for r in rows}


def qids(path=None):
    """The same set as `dsgdb9nsd_XXXXXX` identifiers, matching the rest of this repo."""
    return {"dsgdb9nsd_{:06d}".format(i) for i in indices(path)}


_BY_INDEX = {}


def entry(qm9_index, path=None):
    """Look up one molecule. `qm9_index` may be an integer or `dsgdb9nsd_XXXXXX`.

    Returns that row (with all three SMILES columns) when the molecule is on the list,
    and None when it is not.

    **The dictionary is built once per path**: this function is called once per
    molecule, 133884 times, and a linear scan of 3054 rows would turn that into
    4 x 10^8 comparisons.
    """
    rows, _ = load(path)
    key = str(Path(path or DEFAULT_PATH))
    if key not in _BY_INDEX:
        _BY_INDEX[key] = {r["index"]: r for r in rows}
    return _BY_INDEX[key].get(_to_int(qm9_index))


def _to_int(qm9_index):
    if isinstance(qm9_index, int):
        return qm9_index
    s = str(qm9_index)
    if s.startswith("dsgdb9nsd_"):
        s = s[len("dsgdb9nsd_"):]
    return int(s.lstrip("0") or "0")


def provenance(path=None):
    return load(path)[1]
