#!/bin/bash
# =======================================================================================
# 02d-2 SUBMIT. Reads settings.tsv, writes one conf per row, does the array arithmetic,
# submits ONE job array whose every task holds G cards and runs G rows at once.
#
#     source /APP/u22/ai_x86/toolshs/set-XY-I.sh
#     bash examples/02d-2_qha_settings_array/submit_array.sh [--plan] [array.conf]
#
# THE ARITHMETIC (Slurm job arrays: slurm.schedmd.com/job_array.html)
#     N     rows in settings.tsv
#     T     = ceil(N / GPUS_PER_JOB)          array tasks  (--array=0-(T-1))
#     G     = ceil(N / T)                     cards per task, balanced (--gpus=G)
#     row   = task_id * G + k,  k in 0..G-1   which rows a task runs, one per card
#
# Every array task is one Slurm job with `--gpus=G --cpus-per-task=12G` in the
# fine-grained environment (1 card = 12 CPUs = 120 GB; -G mandatory; --mem forbidden).
# Inside it, array.slurm launches G copies of examples/chain_body.sh, each on its own
# card via S0_CARD=k CUDA_VISIBLE_DEVICES=k, and waits for all of them.
#
# WHAT IS A FILE AND WHAT IS NOT. Each row's settings are written to
# generated/<NAME>.conf BEFORE submission and the job sources that file, so what ran is
# something you can diff -- the same rule as every other conf here. generated/manifest
# lists them in row order and is the only thing the job reads to find its work.
# =======================================================================================
set -eo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
HERE=examples/02d-2_qha_settings_array

PLAN=0
CONF="$HERE/array.conf"
for a in "$@"; do
    case "$a" in
        --plan) PLAN=1 ;;
        *) CONF="$a" ;;
    esac
done
[ -f "$CONF" ] || { echo "no such conf: $CONF" >&2; exit 2; }
# shellcheck disable=SC1090
source "$CONF"
SPECIES="${SPECIES:?array.conf must set SPECIES}"
BASIN_TAG="${BASIN_TAG:?array.conf must set BASIN_TAG}"
TAG_PREFIX="${TAG_PREFIX:-02d2}"
SETTINGS="${SETTINGS:-$HERE/settings.tsv}"
GPUS_PER_JOB="${GPUS_PER_JOB:-8}"
WALLTIME="${WALLTIME:-36:00:00}"     # see array.conf: p1500 needs ~25.8 h
SUBMIT="${OPENQHA_SUBMIT:-yhbatch}"
[ -f "$SETTINGS" ] || { echo "no settings file: $SETTINGS" >&2; exit 2; }

# ---- the basins must exist, once, before N jobs go looking for them --------------------
BASINS_ROOT="${S0_BASIN_ROOT:-data/basins}"
if ! find "$BASINS_ROOT/$BASIN_TAG" -name "${SPECIES}.basins.json" -print -quit 2>/dev/null \
     | grep -q .; then
    echo "openQHA: no branch A product for '$SPECIES' under BASIN_TAG '$BASIN_TAG'." >&2
    echo "  Every row reads it. Make it once, on the CPU cluster:" >&2
    echo "    bash examples/run_chain.sh examples/02d_qha_frequency_identity/branchA.conf deimos            # acetone" >&2
    echo "    bash examples/run_chain.sh examples/02d_qha_frequency_identity/branchA-propanal.conf deimos   # propanal" >&2
    ls -1 "$BASINS_ROOT" 2>/dev/null | sed 's/^/  tags present: /' >&2
    exit 2
fi

# ---- read the rows -----------------------------------------------------------------------
GEN="$HERE/generated"
mkdir -p "$GEN" logs
MANIFEST="$GEN/manifest"
: > "$MANIFEST"
N=0
while read -r name equil prod sample seeds nucut rest; do
    case "$name" in ''|'#'*) continue ;; esac
    [ -n "$nucut" ] || { echo "settings row '$name' is short: need NAME EQUIL PROD SAMPLE SEEDS NU_CUT" >&2; exit 2; }
    tag="${TAG_PREFIX}_${name}"
    conf="$GEN/${name}.conf"
    cat > "$conf" <<EOF
# generated by $HERE/submit_array.sh from $SETTINGS row '$name' on $(date -Is)
# DO NOT EDIT: change settings.tsv and resubmit. This file is what the job sourced.
CHAIN=identity
SPECIES=$SPECIES
TAG=$tag
BASIN_TAG=$BASIN_TAG
EQUIL_PS=$equil
PROD_PS=$prod
SAMPLE_EVERY=$sample
SEEDS=$seeds
NU_CUT=$nucut
THREADS=1
EOF
    echo "$conf" >> "$MANIFEST"
    N=$((N + 1))
done < "$SETTINGS"
[ "$N" -gt 0 ] || { echo "no rows in $SETTINGS" >&2; exit 2; }

# ---- the arithmetic -----------------------------------------------------------------------
T=$(( (N + GPUS_PER_JOB - 1) / GPUS_PER_JOB ))     # array tasks
G=$(( (N + T - 1) / T ))                            # cards per task, balanced
CPUS=$(( 12 * G ))
LAST=$(( N - (T - 1) * G ))                         # rows in the last task
JOB_NAME="openqha_${SPECIES}_${TAG_PREFIX}_array"

echo "02d-2 plan"
echo "  species    $SPECIES     basins from  $BASIN_TAG"
echo "  rows       $N   ($SETTINGS)"
echo "  array      $T task(s), --array=0-$((T - 1))"
echo "  per task   --gpus=$G --cpus-per-task=$CPUS   (1 card = 12 CPUs = 120 GB)"
if [ "$LAST" -lt "$G" ]; then
    echo "  last task  $LAST row(s) on $G cards: $((G - LAST)) card(s) idle for its duration"
fi
echo "  MaxSubmit  10 on this account; this array uses $T"
echo "  confs      $GEN/<NAME>.conf   manifest $MANIFEST"
i=0
while read -r c; do
    t=$(( i / G )); k=$(( i % G ))
    printf '    row %2d  task %d card %d  %s\n' "$i" "$t" "$k" "$(basename "$c" .conf)"
    i=$((i + 1))
done < "$MANIFEST"

# ---- the environment check: same effect-based test as run_chain.sh ----------------------
if [ "${OPENQHA_SKIP_ENV_CHECK:-}" != "1" ] && command -v sinfo >/dev/null 2>&1; then
    if ! sinfo -h -p ai -o %G 2>/dev/null | grep -qi gpu; then
        echo "openQHA: this shell is in TianheXY-A's DEFAULT Slurm environment; a card" >&2
        echo "  request there is refused. First:  source /APP/u22/ai_x86/toolshs/set-XY-I.sh" >&2
        exit 2
    fi
fi

CMD=("$SUBMIT" --job-name="$JOB_NAME" --array="0-$((T - 1))" \
     --nodes=1 --ntasks=1 --gpus="$G" --cpus-per-task="$CPUS" --time="$WALLTIME" \
     "$HERE/array.slurm" "$MANIFEST" "$G")
echo
echo "submit    ${CMD[*]}"
echo "  logs      logs/${JOB_NAME}_<arrayjob>_<task>.{out,err}  and  logs/${TAG_PREFIX}_<NAME>_<arrayjob>_<task>.log"
[ "$PLAN" = "1" ] && { echo "  (--plan: not submitted)"; exit 0; }
exec "${CMD[@]}"
